baseURL: https://girishshekhar.github.io/blog
title: Girish Shekhar
languageCode: en-us

theme:
  - PaperMod

module:
  imports:
    - path: github.com/girishshekhar/girishshekhar-theme

server:
  port: 1314

params:
  author: Girish Shekhar
  mainSiteURL: https://girishshekhar.github.io
  blogSiteURL: https://girishshekhar.github.io/blog
  linkedinURL: https://www.linkedin.com/in/girishshekhar
  
# environments:
#   development:
#     params:
#       mainSiteURL: http://localhost:1313
#       blogSiteURL: http://localhost:1314

